// ignore_for_file: public_member_api_docs,constant_identifier_names,type=lint,unused_element,unused_field
import 'package:flutter/foundation.dart';

//
// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************
// Generated by flutter-assets-generator extension for VS Code
// @mrasityilmaz
// **************************************************************************

@immutable
final class Assets {
  Assets._();
  static final _Fonts fonts = _Fonts._();
  static final _Images images = _Images._();


}

@immutable
final class _Fonts {
  _Fonts._();

  final String cairo_bold_ttf = 'assets\fonts\Cairo-Bold.ttf';
  final String cairo_medium_ttf = 'assets\fonts\Cairo-Medium.ttf';
  final String cairo_regular_ttf = 'assets\fonts\Cairo-Regular.ttf';
  final String cairo_semibold_ttf = 'assets\fonts\Cairo-SemiBold.ttf';

}

@immutable
final class _Images {
  _Images._();

  final String app_icon_jpg = 'assets\images\app_icon.jpg';
  final String check_svg = 'assets\images\Check.svg';
  final String facebook_icon_svg = 'assets\images\facebook_icon.svg';
  final String google_icon_svg = 'assets\images\google_icon.svg';

}

