// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCUZooUGZQsy9_yV1WV3Cbn7AkMNkpHU4',
    appId: '1:657978893939:web:6b047906b0e1029db36c06',
    messagingSenderId: '657978893939',
    projectId: 'final-project-73265',
    authDomain: 'final-project-73265.firebaseapp.com',
    storageBucket: 'final-project-73265.firebasestorage.app',
    measurementId: 'G-9VXGG5LRK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOXiI3WpX_W2bjPKOdov-7gEm2-dJfJss',
    appId: '1:657978893939:android:b20efb28677ece0bb36c06',
    messagingSenderId: '657978893939',
    projectId: 'final-project-73265',
    storageBucket: 'final-project-73265.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCl4zUrCAylY8XByw7jGXSVBfUzbbe7Ug',
    appId: '1:657978893939:ios:3f09e368f3ca75a9b36c06',
    messagingSenderId: '657978893939',
    projectId: 'final-project-73265',
    storageBucket: 'final-project-73265.firebasestorage.app',
    androidClientId: '657978893939-1tvv6p8dbkeirhadi88uq2qf3io893vc.apps.googleusercontent.com',
    iosClientId: '657978893939-uigateimdqkeg18pm8m0p2or4p1lka61.apps.googleusercontent.com',
    iosBundleId: 'com.example.mysterybag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCl4zUrCAylY8XByw7jGXSVBfUzbbe7Ug',
    appId: '1:657978893939:ios:3f09e368f3ca75a9b36c06',
    messagingSenderId: '657978893939',
    projectId: 'final-project-73265',
    storageBucket: 'final-project-73265.firebasestorage.app',
    androidClientId: '657978893939-1tvv6p8dbkeirhadi88uq2qf3io893vc.apps.googleusercontent.com',
    iosClientId: '657978893939-uigateimdqkeg18pm8m0p2or4p1lka61.apps.googleusercontent.com',
    iosBundleId: 'com.example.mysterybag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCUZooUGZQsy9_yV1WV3Cbn7AkMNkpHU4',
    appId: '1:657978893939:web:1d1da01335bc0b6cb36c06',
    messagingSenderId: '657978893939',
    projectId: 'final-project-73265',
    authDomain: 'final-project-73265.firebaseapp.com',
    storageBucket: 'final-project-73265.firebasestorage.app',
    measurementId: 'G-8B1XB7JQ5L',
  );
}
