// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQf-dnLE5HaVXQ0xOVV2HnxXcBoSOdLH0',
    appId: '1:1046370397960:web:2d8a67c75ccdd6952986bd',
    messagingSenderId: '1046370397960',
    projectId: 'complemystreybox',
    authDomain: 'complemystreybox.firebaseapp.com',
    storageBucket: 'complemystreybox.firebasestorage.app',
    measurementId: 'G-Y8DBRGRFMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDJWKv5TCl84vdISL3MAA5jfKAyjqw6vQ',
    appId: '1:1046370397960:android:187252597dc2aad32986bd',
    messagingSenderId: '1046370397960',
    projectId: 'complemystreybox',
    storageBucket: 'complemystreybox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnDTl4QuGP9JuxAFtzVK5YCiMpRV4LPIo',
    appId: '1:1046370397960:ios:7ed6ead6e32e0f892986bd',
    messagingSenderId: '1046370397960',
    projectId: 'complemystreybox',
    storageBucket: 'complemystreybox.firebasestorage.app',
    iosBundleId: 'com.example.mysterybag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnDTl4QuGP9JuxAFtzVK5YCiMpRV4LPIo',
    appId: '1:1046370397960:ios:7ed6ead6e32e0f892986bd',
    messagingSenderId: '1046370397960',
    projectId: 'complemystreybox',
    storageBucket: 'complemystreybox.firebasestorage.app',
    iosBundleId: 'com.example.mysterybag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQf-dnLE5HaVXQ0xOVV2HnxXcBoSOdLH0',
    appId: '1:1046370397960:web:725f2c0adb5529082986bd',
    messagingSenderId: '1046370397960',
    projectId: 'complemystreybox',
    authDomain: 'complemystreybox.firebaseapp.com',
    storageBucket: 'complemystreybox.firebasestorage.app',
    measurementId: 'G-J6X1X27KEV',
  );

}