import 'package:flutter/material.dart';
import 'package:mysterybag/core/entities/product_entity.dart';

/// Demo products for testing checkout functionality
/// Note: Using null imageUrl to avoid network requests - will display placeholder/default image
final List<ProductEntity> demoProducts = [
  ProductEntity(
    nameEn: 'Fresh Apples',
    nameAr: 'تفاح طازج',
    code: 'P001',
    description: 'Red delicious fresh apples from the farm',
    price: 45.00,
    reviews: [],
    expirationsMonths: 2,
    numbersOfCalories: 52,
    unitAmount: 1,
    isFeatured: true,
    isOrganic: true,
    imageUrl: const AssetImage("assets/images/apples.png").toString(),
  ),
  ProductEntity(
    nameEn: 'Organic Bananas',
    nameAr: 'موز عضوي',
    code: 'P002',
    description: 'Fresh organic bananas packed with nutrients',
    price: 25.50,
    reviews: [],
    expirationsMonths: 1,
    numbersOfCalories: 89,
    unitAmount: 1,
    isFeatured: true,
    isOrganic: true,
    imageUrl: const AssetImage("assets/images/bananas.png").toString(),
  ),
  ProductEntity(
    nameEn: 'Carrots Bundle',
    nameAr: 'حزمة جزر',
    code: 'P003',
    description: 'Sweet and crunchy carrots',
    price: 30.00,
    reviews: [],
    expirationsMonths: 3,
    numbersOfCalories: 41,
    unitAmount: 1,
    isFeatured: false,
    isOrganic: true,
    imageUrl: const AssetImage("assets/images/carrots.png").toString(),
  ),
  ProductEntity(
    nameEn: 'Tomato Mix',
    nameAr: 'مزيج طماطم',
    code: 'P004',
    description: 'Fresh tomatoes - perfect for salads',
    price: 35.75,
    reviews: [],
    expirationsMonths: 1,
    numbersOfCalories: 18,
    unitAmount: 1,
    isFeatured: true,
    isOrganic: false,
    imageUrl: const AssetImage("assets/images/tomatoes.png").toString(),
  ),
  ProductEntity(
    nameEn: 'Broccoli Fresh',
    nameAr: 'بروكلي طازج',
    code: 'P005',
    description: 'Healthy and nutritious broccoli',
    price: 28.00,
    reviews: [],
    expirationsMonths: 2,
    numbersOfCalories: 34,
    unitAmount: 1,
    isFeatured: false,
    isOrganic: true,
    imageUrl: "assets/images/broccoli.png",
  ),
  ProductEntity(
    nameEn: 'Orange Citrus',
    nameAr: 'برتقال حمضيات',
    code: 'P006',
    description: 'Sweet and juicy oranges',
    price: 40.00,
    reviews: [],
    expirationsMonths: 3,
    numbersOfCalories: 47,
    unitAmount: 1,
    isFeatured: true,
    isOrganic: false,
    imageUrl: "assets/images/oranges.png",
  ),
];
